[versions]
agp = "8.13.2"
kotlin = "2.2.20"
coroutines = "1.10.2"
androidx-core = "1.16.0"
activity = "1.10.1"
appcompat = "1.7.1"
lifecycle = "2.9.1"
material = "1.13.0"
drawer = "1.2.0"
junit = "4.13.2"
test-core = "1.6.1"
test-runner = "1.6.2"
test-junit = "1.2.1"

[libraries]
coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
androidx-core = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }
androidx-activity = { module = "androidx.activity:activity-ktx", version.ref = "activity" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
androidx-lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
androidx-lifecycle-savedstate = { module = "androidx.lifecycle:lifecycle-viewmodel-savedstate", version.ref = "lifecycle" }
material = { module = "com.google.android.material:material", version.ref = "material" }
androidx-drawer = { module = "androidx.drawerlayout:drawerlayout", version.ref = "drawer" }
junit = { module = "junit:junit", version.ref = "junit" }
androidx-test-core = { module = "androidx.test:core-ktx", version.ref = "test-core" }
androidx-test-runner = { module = "androidx.test:runner", version.ref = "test-runner" }
androidx-test-junit = { module = "androidx.test.ext:junit-ktx", version.ref = "test-junit" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
